# Generated by Django 5.2.1 on 2025-10-04 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date and time when this object was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this object was last updated', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this object', primary_key=True, serialize=False)),
                ('object_id', models.CharField(db_index=True, help_text='The ID of the content object', max_length=255, verbose_name='object id')),
                ('value', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], db_index=True, help_text='The type of reaction (like or dislike)', max_length=10, verbose_name='reaction value')),
                ('content_type', models.ForeignKey(help_text='The type of content this reaction is attached to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(help_text='The user who created this reaction', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'reaction',
                'verbose_name_plural': 'reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'user'], name='reaction_content_user_idx'), models.Index(fields=['user', 'value'], name='reaction_user_value_idx'), models.Index(fields=['content_type', 'object_id', 'value'], name='reaction_content_value_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_user_reaction_per_object')],
            },
        ),
    ]
