# Generated by Django 5.2.1 on 2025-10-05 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_user_reaction_per_object',
        ),
        migrations.RenameIndex(
            model_name='reaction',
            new_name='reactions_r_content_f8d067_idx',
            old_name='reaction_content_user_idx',
        ),
        migrations.RenameIndex(
            model_name='reaction',
            new_name='reactions_r_user_id_d2f097_idx',
            old_name='reaction_user_value_idx',
        ),
        migrations.RenameIndex(
            model_name='reaction',
            new_name='reactions_r_content_4b7529_idx',
            old_name='reaction_content_value_idx',
        ),
        migrations.AddField(
            model_name='reaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address for anonymous users', null=True),
        ),
        migrations.AddField(
            model_name='reaction',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Session key for anonymous users', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created this reaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['content_type', 'object_id', 'session_key'], name='reactions_r_content_c8b1fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('session_key__isnull', False), _connector='OR'), name='user_or_session_required'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'content_type', 'object_id'), name='unique_user_reaction_per_object'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'content_type', 'object_id'), name='unique_session_reaction_per_object'),
        ),
    ]
