# Generated by Django 5.2.1 on 2025-10-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielenz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم\u200cها'},
        ),
    ]
