# Generated by Django 5.2.1 on 2025-09-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'مالک'), ('ADMIN', 'مدیر'), ('PREMIUM_USER', 'کاربر ویژه'), ('NORMAL_USER', 'کاربر عادی')], default='NORMAL_USER', help_text='نقش کاربر در سیستم را مشخص می\u200cکند.', max_length=20, verbose_name='نقش کاربری'),
        ),
    ]
