# Generated by Django 5.2.1 on 2025-09-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
