# Generated by Django 5.2.1 on 2025-09-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_remove_user_is_staff_remove_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'یک کاربر با این نام کاربری وجود دارد.'}, help_text='یک نام کاربری منحصر به فرد برای ورود به سیستم.', max_length=150, verbose_name='نام کاربری'),
        ),
    ]
