# Generated by Django 5.2.1 on 2025-10-09 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('movielenz', '0002_alter_movie_options'),
        ('user_account', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteitem',
            options={'ordering': ['-added_at'], 'verbose_name': 'Favorite Item', 'verbose_name_plural': 'Favorite Items'},
        ),
        migrations.AlterModelOptions(
            name='recentlywatcheditem',
            options={'ordering': ['-watched_at'], 'verbose_name': 'Recently Watched Item', 'verbose_name_plural': 'Recently Watched Items'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='watchlistitem',
            options={'ordering': ['-added_at'], 'verbose_name': 'Watchlist Item', 'verbose_name_plural': 'Watchlist Items'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='recentlywatcheditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='recentlywatcheditem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='recentlywatcheditem',
            name='progress_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Playback progress in seconds', null=True, verbose_name='Progress (seconds)'),
        ),
        migrations.AlterField(
            model_name='recentlywatcheditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_watched_entries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='recentlywatcheditem',
            name='watched_at',
            field=models.DateTimeField(db_index=True, verbose_name='Watched At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=False, help_text='Account activation status. Inactive users cannot log in', verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'A user with this email already exists'}, max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this user belongs to', related_name='account_users', related_query_name='account_user', to='auth.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, related_name='users_preferring', to='movielenz.genre', verbose_name='Preferred Genres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='fa', help_text="Example: 'fa' for Persian, 'en' for English", max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrator'), ('PREMIUM_USER', 'Premium User'), ('NORMAL_USER', 'Normal User')], db_index=True, default='NORMAL_USER', help_text='User role in the system', max_length=20, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Subscription End Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Subscription Start Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='free', max_length=10, verbose_name='Subscription Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user', related_name='account_users', related_query_name='account_user', to='auth.permission', verbose_name='User Permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Non-unique username for display purposes', max_length=150, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='favoriteitem',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='user_accoun_user_id_51abbf_idx'),
        ),
        migrations.AddIndex(
            model_name='favoriteitem',
            index=models.Index(fields=['-added_at'], name='user_accoun_added_a_f00375_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlywatcheditem',
            index=models.Index(fields=['user', '-watched_at'], name='user_accoun_user_id_aaa234_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlywatcheditem',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='user_accoun_user_id_afeadd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_accoun_email_bee25c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_status', 'subscription_end_date'], name='user_accoun_subscri_4691cd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_accoun_role_171e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='user_accoun_user_id_06ba4d_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['-added_at'], name='user_accoun_added_a_fb299d_idx'),
        ),
    ]
