# Generated by Django 5.2.1 on 2025-10-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('movielenz', '0002_alter_movie_options'),
        ('user_account', '0006_alter_favoriteitem_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='user_accoun_date_jo_92aa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'activated'], name='user_accoun_is_acti_085308_idx'),
        ),
    ]
