"""
Django settings for movie project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# import dj_database_url  / not installed
import os
from datetime import timedelta

# تغییر ugettext_lazy به gettext_lazy
# from django.utils import translation
# translation.ugettext_lazy = translation.gettext_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
print("------------------------------------")
print("Loading settings.py...")
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    print("ERROR: DJANGO_SECRET_KEY not found in environment variables!")
    raise Exception("Please set the DJANGO_SECRET_KEY environment variable.")
else:
    print(f"DJANGO_SECRET_KEY: {'*' * 5}{SECRET_KEY[-5:]}")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ("true", '1', 't')

DJANGO_DEBUG_ENV_VAR = os.getenv("DJANGO_DEBUG", "True") # مقدار خام از .env یا پیش‌فرض
print(f"settings.py: Raw DJANGO_DEBUG from env (or default): '{DJANGO_DEBUG_ENV_VAR}' (type: {type(DJANGO_DEBUG_ENV_VAR)})")

DEBUG = DJANGO_DEBUG_ENV_VAR.lower() in ("true", '1', 't')
print(f"settings.py: Calculated DEBUG value: {DEBUG} (type: {type(DEBUG)})")


# ALLOWED_HOSTS = []
# ALLOWED_HOSTS_STRING = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
# ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STRING.split(',') if host.strip()]
# ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

ALLOWED_HOSTS_STRING = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
print(f"settings.py: Raw DJANGO_ALLOWED_HOSTS from env (or default): '{ALLOWED_HOSTS_STRING}'")
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STRING.split(',') if host.strip()]
print(f"settings.py: Calculated ALLOWED_HOSTS: {ALLOWED_HOSTS}")

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    
    'django.contrib.sites',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # "type",
    "movielenz",
    "celebrity",
    "episode",
    "user_account",
    "blog",
    "panel",
    'comment',
    'reactions',
    
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
    
    "rest_framework",
    "mptt",
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'polymorphic',       
    'drf_polymorphic',
    'django_filters',
    'pytest_django',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'movie.urls'
AUTH_USER_MODEL = 'user_account.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'your_db_name',
#         'USER': 'your_db_user',
#         'PASSWORD': 'your_db_password',
#         'HOST': 'localhost',  # or your db host
#         'PORT': '5432',       # or your db port
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    print(f"settings.py: DEBUG is True. SECURE_SSL_REDIRECT = {SECURE_SSL_REDIRECT}")
else:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600  # 1 hour
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # SECURE_BROWSER_XSS_FILTER = True # این دیگر توصیه نمی‌شود
    X_FRAME_OPTIONS = 'DENY'
    print(f"settings.py: DEBUG is False. SECURE_SSL_REDIRECT = {SECURE_SSL_REDIRECT}")

print("------------------------------------")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1000), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1000), 
    'ROTATE_REFRESH_TOKENS': True, 
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',), 
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication', 
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication', 
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Comment API Documentation',
    'DESCRIPTION': 'A comprehensive API for the comment system.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}
DRF_POLYMORPHIC_SETTINGS = {
    'TYPE_FIELD': 'object_type'
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# smtp email

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = "hameddjf106@gmail.com"
# EMAIL_HOST_PASSWORD = "aaas ypux cauw lbho"
EMAIL_HOST_PASSWORD = "horx cvwb jgex rmrj"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_VERIFICATION = 'none'
DEFAULT_FROM_EMAIL = 'MovieLenz Support <movielenz.com>'
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[MovieLenz]'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True



REST_AUTH = {
    # 'LOGIN_SERIALIZER': 'user_account.serializers.CustomLoginSerializer',
    'REGISTER_SERIALIZER': 'user_account.serializers.CustomRegisterSerializer',
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
    'PASSWORD_RESET_CONFIRM_URL': "/api/user/password/reset/confirm/{uidb64}/{token}/",
}

# login with account

SITE_ID = 1 # برای کارکرد django.contrib.sites

# برای اینکه جنگو بداند هم با ایمیل لاگین کند و هم از طریق شبکه‌های اجتماعی
AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# تنظیمات برای غیرفعال کردن ایمیل تاییدیه پس از ثبت‌نام با شبکه‌های اجتماعی (اختیاری)
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_REQUIRED = False

# login

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'


# jazzmin

JAZZMIN_SETTINGS = {
    "site_title": "داشبورد",
    "site_header": "movie",
    "site_brand": "movie",
    "welcome_sign": "خوش امدین به پنل ادمین movie",
    "copyright": "movie",
    # "order_sidebar_by": "movie",
    "show_sidebar": True,
    "show_header": True,
    "navigation_expanded": False,
    "custom_css": "css/custom.css",  # آدرس CSS سفارشی
}

# if DEBUG:
#     INSTALLED_APPS += ['debug_toolbar']
#     MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')
#     INTERNAL_IPS = [
#         '127.0.0.1',
#     ]

# token (access / refresh)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

CORS_ALLOW_ALL_ORIGINS = True