# Generated by Django 5.2.1 on 2025-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name to display for this comment', max_length=100, verbose_name='Display Name'),
        ),
        migrations.AddField(
            model_name='comment',
            name='has_spoiler',
            field=models.BooleanField(default=False, help_text='Whether this comment contains spoilers', verbose_name='Has Spoiler'),
        ),
    ]
