# Generated by Django 5.2.1 on 2025-10-05 17:54

import comment.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_display_name_comment_has_spoiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='display_name',
            field=models.CharField(help_text='Name to display for this comment', max_length=100, validators=[comment.validators.validate_display_name], verbose_name='Display Name'),
        ),
    ]
